### PR TITLE
Add travis ci

### PR DESCRIPTION
**Pull request by rgrinberg**
@avsm could you set up travis for this repo? I don't think I have the
credentials

### CODE REVIEW

**Comment by andreypopp** [comment]
Can we go with azure instead so we can test on Windows, macOS and Linux?

**Comment by rgrinberg** [comment]
That makes sense. Do you think the extra testing from travis isn't useful? Or is it just redundant?

Do you want to setup the azure stuff? I assume you have some experience with it in esy already.

**Comment by andreypopp** [comment]
Not redundant, at least for now while we don't have azure configured. Let's go with travis and we can add/replace it with azure later.

**Comment by rgrinberg** [comment]
Alright, let's get some other CI integrations in. I'll make some tickets.

**Pull request merged**
