### PR TITLE
Update vendored merlin to support 4.06

### PR DESCRIPTION
**Pull request by prometheansacrifice**

### CODE REVIEW

**Comment by prometheansacrifice** [comment]
We're green again!

**Comment by tsnobip** [comment]
I can't make ocaml-lsp work with 4.06 and esy because esy doesn't work with an ocaml-secondary-compiler (filed here : esy/esy/issues/1062) which is necesarry when using dune 2. But apparently ocaml-lsp needs dune >= 2, which leads to this error when trying to use ocaml-lsp with dune < 2:

```
info building @opam/ocaml-lsp-server@github:ocaml/ocaml-lsp:ocaml-lsp-server.opam#01a98c7@d41d8cd9
error: build failed with exit code: 1
  build log:
    # esy-build-package: building: @opam/ocaml-lsp-server@github:ocaml/ocaml-lsp:ocaml-lsp-server.opam#01a98c7
    # esy-build-package: pwd: /Users/paul/.esy/3/b/opam__s__ocaml_lsp_server-969915b4
    # esy-build-package: running: 'dune' 'build' '-j' '4' '--root' '.' '--ignore-promoted-rules' '--no-config' '--profile' 'release' 'ocaml-lsp-server.install'
    File "vendor/ocaml-syntax-shims/dune-project", line 1, characters 11-14:
    1 | (lang dune 2.0)
                   ^^^
    Error: Version 2.0 of dune is not supported.
    Supported versions:
    - 0.0
    - 1.0 to 1.11
    error: command failed: 'dune' 'build' '-j' '4' '--root' '.' '--ignore-promoted-rules' '--no-config' '--profile' 'release' 'ocaml-lsp-server.install' (exited with 1)
    esy-build-package: exiting with errors above...
    
  building @opam/ocaml-lsp-server@github:ocaml/ocaml-lsp:ocaml-lsp-server.opam#01a98c7
```
Would it be possible to have ocaml-lsp work with dune 1 while this issue is not fixed on esy? 

Even if not doable, this post could help people struggling with the same issue.

**Comment by prometheansacrifice** [comment]
Hey, thanks for the report. ocaml-lsp does work with Dune 2.0.1 with esy.
Can you please take a look at esy.json at vscode-merlin mean time we fix it.

Let me know if you have any trouble with it

**Comment by tsnobip** [comment]
thanks @prometheansacrifice, I managed to make it work with the given resolutions : 
```
  "resolutions": {
    "@opam/ocaml-lsp-server": "github:ocaml/ocaml-lsp:ocaml-lsp-server.opam#3e20872",
    "@opam/dune": "2.0.1",
    "@opam/dune-configurator": "2.0.1",
    "@opam/atd": "github:ahrefs/atd:atd.opam#0ef770a",
    "@opam/atdgen-runtime": "github:ahrefs/atd:atdgen-runtime.opam#0ef770a",
    "@opam/atdgen": "github:ahrefs/atd:atdgen.opam#0ef770a",
    "@opam/menhir": "20200123",
    "@opam/menhirSdk": "20200123",
    "@opam/menhirLib": "20200123",
    "@opam/dune-private-libs": "2.0.1"
  }
```

**Comment by prometheansacrifice** [comment]
Are the atdgen overrides necessary too?

**Comment by prometheansacrifice** [comment]
I mean to ask, what build errors do you see without atdgen overrides?

**Comment by tsnobip** [comment]
Yes they are necessary otherwise esy complains with the following error:
```
unable to resolve command: jbuilder
```
because I guess the opam published version of atd still requires jbuilder and not dune

**Pull request merged**
