### PR TITLE
opam pin commands are needed

### PR DESCRIPTION
**Pull request by UnixJunkie**
so that instructions in the README actually work...

### CODE REVIEW

**Comment by imbsky** [comment]
I wonder if we should write this in the README because this is still a working in progress project.

**Comment by imbsky** [comment]
People who want to use this at this point probably don't need this, and beginners just get confused.

**Comment by UnixJunkie** [comment]
Advertising non working install instructions is just annoying. You can still update the README later if this becomes non necessary.

**Comment by imbsky** [comment]
Well, I'll leave it to @rgrinberg. I understand your opinion.

**Comment by rgrinberg** [comment]
Thanks

**Pull request merged**
