### PR TITLE
Move from npm to yarn

### LINKED ISSUE #7: Move tests from npm to yarn

### PR DESCRIPTION
**Pull request by imbsky**
Closes #7

### CODE REVIEW

**Comment by imbsky** [comment]
I upgraded the package version in first commit of this PR, so we can also close Dependabot's PR.

**Comment by andreypopp** [comment]
Thanks! Let's land after #6 (this PR likely will needed to be rebased).

Wondering why is there changes after prettier? Is it because of a newer prettier version or just a different config? We'd likely need to drop `.prettierrc` inside `e2e` dir so that all contributors have the same config for prettier (and not a user specific one).

**Comment by imbsky** [comment]
Yes, sure. So when #6 is merged, I will rebase and add the prettier configuration file.

**Comment by rgrinberg** [comment]
#6 is now merged.

**Comment by imbsky** [comment]
It seems that the code style was changed due to a version.

**Comment by imbsky** [comment]
npm modules often have problems, so I pinned all dependencies.

**Comment by rgrinberg** [comment]
@andreypopp mind reviewing this one?

**Pull request merged**
