### PR TITLE
Upgrade OCaml version in CI

### PR DESCRIPTION
**Pull request by ulugbekna**

### CODE REVIEW

**Comment by ulugbekna** [comment]
@rgrinberg do you know off the top of your head why URI tests are failing on windows? otherwise, I can take a look

**Review by smorimoto — APPROVED** [review]

**Comment by smorimoto** [comment]
To me, the content of the test doesn't seem appropriate in the first place.

**Comment by tatchi** [comment]
From what I see in the code, a `/` is [prepended to the path](https://github.com/ocaml/ocaml-lsp/blob/master/lsp/src/uri0.ml#L52) on every platform except windows. I guess that's probably why it fails on this platform.

**Comment by ulugbekna** [comment]
Windows-related failures can be fixed in another PR. 

I'm not sure, but should nix-related files be updated to the new compiler? Also can happen in another PR.

**Pull request merged**
