### PR TITLE
Fix crash in the Merlin pipeline

### PR DESCRIPTION
**Pull request by anmonteiro**
[This line](https://github.com/rgrinberg/merlin/blob/e757fe8f9276c87154356171959fabc806f4488e/src/extend/extend_driver.ml#L45) in the Merlin Extend driver (used by Reason's `ocamlmerlin-reason`) can throw a `Unix.Error (ECHILD, _,_)`.

This fix avoids crashing the OCaml LSP Server when that happens.

### CODE REVIEW

**Comment by anmonteiro** [comment]
This just fixes the symptom of what I'm seeing. It might not be related to LSP. 

Though I'm not sure what the behavior should be here. Clearly, `Mpipeline.with_pipeline` can throw, and that's not currently being handled.

**Comment by rgrinberg** [comment]
> [This line](https://github.com/rgrinberg/merlin/blob/e757fe8f9276c87154356171959fabc806f4488e/src/extend/extend_driver.ml#L45) in the Merlin Extend driver (used by Reason's ocamlmerlin-reason) can throw a Unix.Error (ECHILD, _,_).

That's indeed suspicious. The most reliable way to fix this is to rewrite the driver to use `Lev_fiber` and use Async IO and `Lev_fiber.waitpid`.

I'm not even sure how this is fixing anything. It seems like you're just wrapping the exception with Code_error?

**Comment by anmonteiro** [comment]
> That's indeed suspicious. 

I believe it's some PPX doing unspeakable things (e.g. including Marshaled output in `external` payload) and killing whatever transport it passes through here. Still trying to track that down.

> The most reliable way to fix this is to rewrite the driver to use Lev_fiber and use Async IO and Lev_fiber.waitpid.

Where? In the Merlin reader code?

**Comment by rgrinberg** [comment]
> Where? In the Merlin reader code?

That's right. We have a merlin fork where we apply changes like that.

**Comment by rgrinberg** [comment]
See #735

**Pull request closed without merging**
