### PR TITLE
Bump minimum required dune version to 2.0

### PR DESCRIPTION
**Pull request by imbsky**

### CODE REVIEW

**Comment by rgrinberg** [comment]
I think the minimum is 2.3 actually. This can be cross referenced with the dune-project file.

**Comment by imbsky** [comment]
What does cross-reference mean?

**Comment by rgrinberg** [comment]
I mean that the language set in dune-project and the minimum version of dune should agree.

**Comment by rgrinberg** [comment]
Wait sorry, I was looking at a different project. Indeed 2.0 is enough for ocaml-lsp. Sorry for the noise.

**Comment by imbsky** [comment]
No worries

**Pull request merged**
