### PR TITLE
test: add tests for exit and shutdown notifications

### PR DESCRIPTION
**Pull request by jchavarri**
As requested in https://github.com/ocaml/ocaml-lsp/pull/1239#issuecomment-2061097336.

It seems that the `ocamllsp` server behaves according to the [spec](https://microsoft.github.io/language-server-protocol/specifications/lsp/3.17/specification/#exit), except for the case where `Exit` is sent without a previous `Shutdown`, in which case it exits with code 0, but it should be 1.

### CODE REVIEW

**Comment by jchavarri** [comment]
The tests are failing because the changelog is missing, but I don't think this PR deserves an entry.

**Review by rgrinberg — CHANGES_REQUESTED** [review]
Why did you decide to copy paste `Test.T` into your test case? I might be missing something

**Review by rgrinberg — CHANGES_REQUESTED** [review]
Why did you decide to copy paste `Test.T` into your test case? I might be missing something

**Comment by jchavarri** [comment]
> Why did you decide to copy paste `Test.T` into your test case? I might be missing something

To be able to print stuff to the console on specific places that were not covered in `Test.T`, for example look for the strings `"ocamllsp finished with code = %d@.%!"` or `"ocamllsp process timed out\n"`.

**Comment by rgrinberg** [comment]
It's still way too much copy pasting to justify adding 3 print statements. You could instead modify the run function to return the status of the process when it's finished

**Comment by jchavarri** [comment]
Tried something in https://github.com/ocaml/ocaml-lsp/pull/1241/commits/7e73fea1126d8da93277f758123d3b8375d21c1d. I wasn't too sure how to pass the status through the `Fiber.all_concurrently` function (which expects all fibers to return a uniform type), so tried to handle it with a new variant type + unwrap with exceptions right after it.

**Pull request merged**
