### PR TITLE
friendlier code action name for type-annotate

### PR DESCRIPTION
**Pull request by ulugbekna**

### CODE REVIEW

**Comment by rgrinberg** [comment]
cc @Khady for review

**Comment by Khady** [comment]
Definitely fine by me. Maybe the file should be renamed too?

**Review by Khady — APPROVED** [review]
Thanks

**Comment by ulugbekna** [comment]
@rgrinberg merging this. Let me know if you prefer to do merges yourself in the future (I just wanted to take this off your plate). 

Also let me know if you have preferences regarding merge/squash-merge/rebase-merge/etc.

**Comment by rgrinberg** [comment]
I assigned it to Khady, so his approval is sufficient here to merge by anyone. I prefer to avoid merge commits, but it does not matter too much.

**Pull request merged**
