### PR TITLE
fix crash when trace is set to messages

### PR DESCRIPTION
**Pull request by tatchi**
Should fix https://github.com/ocamllabs/vscode-ocaml-platform/issues/587

### CODE REVIEW

**Comment by tatchi** [comment]
I can confirm that with this change, traces are correctly printed in the VScodes's output window

image

**Comment by rgrinberg** [comment]
[According to the spec](https://microsoft.github.io/language-server-protocol/specifications/specification-current/#traceValue), `"message"` is correct.

**Comment by tatchi** [comment]
> [According to the spec](https://microsoft.github.io/language-server-protocol/specifications/specification-current/#traceValue), `"message"` is correct.

Interesting! Looks like that was a change introduced in the current version (3.16) since the previous spec (3.15) uses `messages`: https://microsoft.github.io/language-server-protocol/specifications/specification-3-15/#initialize

**Comment by rgrinberg** [comment]
Perhaps we need to upgrade our libraries in vscode?

**Comment by tatchi** [comment]
> Perhaps we need to upgrade our libraries in vscode?

That's what I was looking into indeed. We use [version 7 of the `vscode-languageclient`](https://github.com/ocamllabs/vscode-ocaml-platform/blob/master/package.json#L843) which appears [to be the latest](https://www.npmjs.com/package/vscode-languageclient)

Also looking at the lsp code, `messages` looks to be correct: https://github.com/microsoft/vscode-languageserver-node/blob/main/jsonrpc/src/common/connection.ts#L205

That's also what typescript uses:

Screenshot 2021-04-22 at 07 25 49

That's probably an error in their doc?

**Comment by rgrinberg** [comment]
Okay, can you raise an issue in the spec repo about this please?

**Comment by giltho** [comment]
[That's on me](https://github.com/microsoft/language-server-protocol/pull/953/files) sorry...

I'll write the PR to fix that

**Pull request merged**
