### PR TITLE
fix windows URI parsing bug (mentioned in #184 at the end)

### PR DESCRIPTION
**Pull request by ulugbekna**
I hope I got this right this time. 

It'd be great if someone could test it on windows in particular (@db4 or @smorimoto maybe?)

### CODE REVIEW

**Comment by rgrinberg** [comment]
@mnxn has a windows machine as well

**Comment by mnxn** [comment]
If I switch from an existing `a.ml` to an untitled scheme `a.mli` and try to switch back, it doesn't work.

Switching to `a.mli`:
```
[Trace - 8:52:03 AM] Sending request 'ocamllsp/switchImplIntf - (4)'.
Params: "file:///c:/dev/projects/promise_jsoo/a.ml"


[Trace - 8:52:03 AM] Received response 'ocamllsp/switchImplIntf - (4)' in 1ms.
Result: [
    "file:///c%3A/dev/projects/promise_jsoo/a.mli"
]
```

Trying to switch back to `a.ml`:
```
[Trace - 8:52:10 AM] Sending request 'ocamllsp/switchImplIntf - (5)'.
Params: "untitled:/c:/dev/projects/promise_jsoo/a.mli"


[Trace - 8:52:10 AM] Received response 'ocamllsp/switchImplIntf - (5)' in 1ms.
Result: [
    "file:////c%3A/dev/projects/promise_jsoo/a.ml"
]
```

I think the problem is the 4 forward slashes in `file:////c%3A/dev/projects/promise_jsoo/a.ml`.

The developer console has this error:
```
[UriError]: If a URI does not contain an authority component, then the path cannot begin with two slash characters ("//")
```

**Comment by ulugbekna** [comment]
1) I don't have a windows machine and installing windows virtual box doesn't allow to have WSL to install opam et al., does anybody know what I could do? 

2) I used `Str` module here. Should I replace it with something else because of thread-safety?

**Comment by rgrinberg** [comment]
Yes, please drop it. Consider one of:

* Do not use regular expressions at all if its simple enough.
* Use ocamllex
* Use re if regular expressions cannot be avoided.

**Comment by mnxn** [comment]
>  1. I don't have a windows machine and installing windows virtual box doesn't allow to have WSL to install opam et al., does anybody know what I could do?

@ulugbekna: I don't think installing WSL will help test for Windows since it will act like linux.

You can install [OCaml for Windows](https://fdopen.github.io/opam-repository-mingw/installation/) for a native mingw Windows version. It's what Esy uses under the hood on Windows.

**Pull request closed without merging**
