### PR TITLE
Attempt to update metaModel

### PR DESCRIPTION
**Pull request by qua3k**
I'm not exactly sure how to generate the types. Running `dune runtest --auto-promote && dune fmt --auto-promote` just deleted a bunch of code.

### CODE REVIEW

**Comment by qua3k** [comment]
Fixes #1056

**Comment by rgrinberg** [comment]
you can run `dune build @cinaps --auto-promote; dune build @fmt --auto-promote` to regenerate from the metamodel.

**Comment by qua3k** [comment]
> you can run `dune build @cinaps --auto-promote; dune build @fmt --auto-promote` to regenerate from the metamodel.

I did that, but there is no difference.

**Comment by qua3k** [comment]
Actually, I think that the changes I made are really broken. The type alias for Uri to string was removed, so there was some trouble where it was undefined, and I tried to have it directly be defined as a string, but that broke a bunch of other code that expected a Uri.t.

**Comment by rgrinberg** [comment]
How about we start with porting only the change to metamodel that's required to fix the issue with DocumentSelector? Later, we can worry about updating everything else.

**Comment by qua3k** [comment]
> How about we start with porting only the change to metamodel that's required to fix the issue with DocumentSelector? Later, we can worry about updating everything else.

Okay, so I reset my branch to HEAD@master but I get the same error after running `dune build @cinaps --auto-promote; dune build @fmt --auto-promote`

How did you generate this previously?

```
duckie@macbook ocaml-lsp λ make all                                  
dune build @all
File "lsp/src/types.ml", line 1345, characters 42-53:
1345 |     Json.To.literal_field "kind" "delete" yojson_of_t t
                                                 ^^^^^^^^^^^
Error: Unbound value yojson_of_t
Hint: Did you mean yojson_of_int?
Hint: If this is a recursive definition,
you should add the 'rec' keyword on line 1344
make: *** [all] Error 1
```

**Pull request closed without merging**
