### PR TITLE
Handle workspace change notifications

### PR DESCRIPTION
**Pull request by rgrinberg**
The server will now maintain the set of open workspace folders and use
this set for querying symbols.

Support for dune is a bit more complicated, but the idea is going to be manage a dune connection per workspace folder.

### CODE REVIEW

**Comment by voodoos** [comment]
I just tried the new RPC mechanism with this PR and Dune master and got a crash.

Here is the "OCaml Language Server" output: 
```
ocamllsp: internal error, uncaught exception:
          Abort: /-----------------------------------------------------------------------
          | Internal error: Uncaught exception.
          | Response.E
          |   { payload = Some [ [ "id"; [ "initialize" ] ] ]
          |   ; message =
          |       "connection terminated. this request will never receive a response"
          |   ; kind = Code_error
          |   }
          | Raised at Dune_rpc_private.Client.Make.connect_raw.run in file "submodules/dune/otherlibs/dune-rpc/private/dune_rpc_private.ml", line 926, characters 21-47
          | Called from Fiber.Execution_context.run_jobs in file "submodules/dune/src/fiber/fiber.ml", line 204, characters 8-13
          | Re-raised at Stdune__Exn.raise_with_backtrace in file "submodules/dune/otherlibs/stdune-unstable/exn.ml" (inlined), line 36, characters 27-56
          | Called from Stdune__Exn_with_backtrace.reraise in file "submodules/dune/otherlibs/stdune-unstable/exn_with_backtrace.ml", line 18, characters 33-71
          | Called from Fiber.Execution_context.forward_error in file "submodules/dune/src/fiber/fiber.ml" (inlined), line 132, characters 4-43
          | Called from Fiber.Execution_context.run_jobs in file "submodules/dune/src/fiber/fiber.ml", line 208, characters 6-23
          | Called from Fiber.Execution_context.run.(fun).loop in file "submodules/dune/src/fiber/fiber.ml", line 226, characters 12-27
          | Called from Stdune__Exn.protectx in file "submodules/dune/otherlibs/stdune-unstable/exn.ml", line 12, characters 8-11
          | Re-raised at Stdune__Exn.protectx in file "submodules/dune/otherlibs/stdune-unstable/exn.ml", line 18, characters 4-11
          | Called from Fiber_unix__Scheduler.run_result in file "fiber-unix/src/scheduler.ml", line 413, characters 10-27
          \-----------------------------------------------------------------------
          
          
          Raised at Fiber_unix__Scheduler.run in file "fiber-unix/src/scheduler.ml", line 428, characters 15-30
          Called from Cmdliner_term.app.(fun) in file "ocaml-lsp-server/vendor/cmdliner/src/cmdliner_term.ml", line 25, characters 19-24
          Called from Cmdliner.Term.run in file "ocaml-lsp-server/vendor/cmdliner/src/cmdliner.ml", line 117, characters 32-39
[Info  - 6:20:33 PM] Connection to server got closed. Server will restart.
```
          
          
Dune watch output:
```
Error: encountered error serving rpc client (id 26)
("attempting to write to a closed channel",
{ sexp =
    [ [ [ "id"; [ "initialize" ] ]
      ; [ "result"
        ; [ "error"
          ; [ [ "kind"; "Invalid_request" ]
            ; [ "message"; "invalid method" ]
            ; [ "payload"; [ [ "method"; "initialize" ] ] ]
            ]
          ]
        ]
      ]
    ]
})
backtrace:
Raised at Stdune__code_error.raise in file
"otherlibs/stdune-unstable/code_error.ml", line 11, characters 30-62
Called from Fiber.Execution_context.apply in file "src/fiber/fiber.ml", line
182, characters 9-14
```

Restarting Dune's watch and editing/saving a few times triggers the same crash.

**Comment by rgrinberg** [comment]
Which version (commit hash) of dune were you using?

**Comment by rgrinberg** [comment]
Another thing to make it easier to debug is to set `DUNE_RPC_DEBUG=1` for both the client and the server. This will allow you to see the traffic for both.

**Comment by voodoos** [comment]
> Which version (commit hash) of dune were you using?

2.8.0-777-gebfc996 (Fix compilation on Haiku, Sep 2)

**Comment by voodoos** [comment]
It did not happen again in a short session of coding. It might be because I wrongfully pinned `ocaml-lsp-server` without the other packages in `ocamllsp` (`lsp`, `jsonrpc` etc).

I will have to stop testing, the 100% cpu from `dune -w` is becoming unbearable...

**Comment by rgrinberg** [comment]
>  I will have to stop testing, the 100% cpu from dune -w is becoming unbearable...
Are you testing on macos or linux?

**Comment by rgrinberg** [comment]
> I will have to stop testing, the 100% cpu from dune -w is becoming unbearable...

Should be fixed by https://github.com/ocaml/dune/pull/4893

**Pull request merged**
