### PR TITLE
feature: move to our own merlin config reading

### PR DESCRIPTION
**Pull request by rgrinberg**
This fixes issues with merlin running its own processes. In the future,
we'll try and re-use dune rpc instead of running yet another binary.

cc @voodoos

### CODE REVIEW

**Comment by voodoos** [comment]
(I did not look at the PR in depth)
You bypass Merlin spinning up `dot-merlin-reader` by not calling `Mconfig.get_external_config`, that seems a reasonable thing to do but what was the initial issue that led you to do this change ?

I also agree that the next obvious step is to use Dune RPC to get the configuration. 

However would that mean that the user would have to have Dune's watch mode running in order to get configuration ?

**Comment by gares** [comment]
Hello, I just found out about this while working with @clodyhug on a project which does not use dune for building.
Is there a way to convert by hand a working .merlin file into the (usually dune generated) metadata the lsp server reads?

**Comment by rgrinberg** [comment]
Ocamllsp now reads the metadata by directly querying dune. So there's no way to provide it manually at all.

One workaround is to write dune files for development only. This is what the OCaml compiler does to provide merlin/lsp support for example. It's a bit more boilerplate, but at least your lsp configuration is guaranteed to be correct.

**Comment by gares** [comment]
You also need to build with dune, otherwise the cmi are not in the right place.

Assuming everything is built with dune is kind of harsh. At least the error should be clear: no dune file, no intellisense.

**Comment by rgrinberg** [comment]
Granted, it's at little harsh. The old system had its costs in usability though. I'd get numerous issues from people misconfiguring lsp with stray .merlin files and the additional dependency isn't great either. In the future, I'd like to rely on dune for even more functionality so I just thought we should bite the bullet now.

**Comment by gares** [comment]
btw, the error I was getting wan even harder to understand, like a missing -rectypes... go figure.

**Comment by voodoos** [comment]
@gares it is not a very satisfying solution, but you might be able to work with the [deprecated OCaml extension](https://marketplace.visualstudio.com/items?itemName=hackwaly.ocaml) from @hackwaly. It still works quite well with recent versions of Merlin (I am using it when performing upgrades to newer version of OCaml that are thus not supported by ocaml-lsp yet).

And because it uses vanilla Merlin and Merlin keeps reading `.merlin` files when they are present it should work out of the box. (But other issues might appear since the development of this extension stopped).

(For it to work with my 4.14 version of Merlin I have to write the absolute path to the precise binary `/home/tom/.opam/414-shapes-opt/bin/ocamlmerlin` in the settings and reload the window.)

**Comment by maxkorp** [comment]
Small note since I'm looking at a partial reversion, the commit listed here seems to have gone poof from the repo history, the new sha for where it ended up is ebc0032c44e84eefd9ed809d064d6bfac0b51d7b

https://github.com/ocaml/ocaml-lsp/commit/ebc0032c44e84eefd9ed809d064d6bfac0b51d7b

**Pull request merged**
