### PR TITLE
debug changes

### PR DESCRIPTION
**Pull request by rgrinberg**
@copy could you try reproducing the issue with this PR?

You need to set the log file with an environment variable: `OCAMLLSP_DEBUG_CHANGES=ocamllsp.log`. Then, just reproduce the bug and paste the first change set that introduces the incorrect document.

### CODE REVIEW

**Comment by ulugbekna** [comment]
I can reproduce but seemingly not if I rebase onto #1005 

I have a suspicion that we may be changing the document in the store with an older version of it.

**Comment by ulugbekna** [comment]
I also think that when auto-save is on, we try sending in a `task_if_running` diagnostics a lot more often, it could be possible that we compute diagnostics for a version of document that's older than the one in doc store?

**Comment by rgrinberg** [comment]
> I also think that when auto-save is on, we try sending in a task_if_running diagnostics a lot more often, it could be possible that we compute diagnostics for a version of document that's older than the one in doc store?

I don't think it would matter. An additional save in the end would fix the situation with the diagnostics. While @copy was telling us that doing additional saves at the end does not change anything.

**Comment by rgrinberg** [comment]
the bug is fixed

**Pull request closed without merging**
