### PR TITLE
Fix URI handling on Windows

### PR DESCRIPTION
**Pull request by rgrinberg**
Signed-off-by: Rudi Grinberg <me@rgrinberg.com>

### CODE REVIEW

**Comment by rgrinberg** [comment]
@mnxn see if this works for you.

**Comment by rgrinberg** [comment]
I got rid of encoding the colon in the path. Vscode isn't doing it on incoming requests.

**Comment by mnxn** [comment]
Switching to an interface file still works fine, but the unbound modules are still there.

There's a problem reported to VSCode:
```
{
	"resource": "/c:/Users/Max/Projects/vscode-ocaml-platform/src/ocaml_lsp.ml",
	"owner": "_generated_diagnostic_collection_name_#0",
	"severity": 8,
	"message": "No config found for file \"ocaml_lsp.ml\" in \"c%3a\\\\users\\\\max\\\\projects\\\\vscode-ocaml-platform\\\\src\". Try calling `dune build`.",
	"source": "ocamllsp",
	"startLineNumber": 2,
	"startColumn": 1,
	"endLineNumber": 3,
	"endColumn": 1
}
```

This time there's an exception in the log, but I don't know if it's related:
```
[Trace - 5:53:55 PM] Received response 'textDocument/codeAction - (2)' in 8ms. Request failed: uncaught exception (-32603).
Error data: {
    "exn": "(\"Fdecl.get: not set\", {})",
    "backtrace": "Raised at Stdune__Code_error.raise in file \"vendor/stdune-unstable/code_error.ml\", line 9, characters 30-62\nCalled from Stdune__Fdecl.get in file \"vendor/stdune-unstable/fdecl.ml\" (inlined), line 29, characters 13-53\nCalled from Stdune__Path.make_local_path in file \"vendor/stdune-unstable/path.ml\", line 816, characters 26-60\nCalled from Stdune__Path.of_string in file \"vendor/stdune-unstable/path.ml\" (inlined), line 845, characters 18-51\nCalled from Dune__exe__Inference.force_open_document in file \"ocaml-lsp-server/src/inference.ml\", line 41, characters 26-52\nCalled from Dune__exe__Inference.infer_intf in file \"ocaml-lsp-server/src/inference.ml\", line 65, characters 22-56\nCalled from Dune__exe__Action_inferred_intf.code_action in file \"ocaml-lsp-server/src/code_actions/action_inferred_intf.ml\", line 19, characters 16-68\nCalled from Dune__exe__Ocaml_lsp_server.code_action.code_action in file \"ocaml-lsp-server/src/ocaml_lsp_server.ml\", line 177, characters 24-28\nCalled from Fiber.Execution_context.apply in file \"vendor/fiber/fiber.ml\", line 196, characters 9-14\n"
}


[Error - 5:53:55 PM] Request textDocument/codeAction failed.
  Message: uncaught exception
  Code: -32603 
[object Object]
```

**Comment by rgrinberg** [comment]
>There's a problem reported to VSCode (the project is built):

Try again. I reverted the change to `:`.

> This time there's an exception in the log, but I don't know if it's related:

It does not seem to be related. I pushed a fix for it nonetheless.

**Review by mnxn — APPROVED** [review]
That seems to have fixed it. No more problems here.

**Pull request merged**
