### PR TITLE
refactor: switch to lev_fiber from home scheduler

### PR DESCRIPTION
**Pull request by rgrinberg**

### CODE REVIEW

**Comment by ulugbekna** [comment]
Hi, great to see this PR, thanks! :-) 

Is it okay if I review the PR by tomorrow midnight? I'd like to first read about libev and lev. 

Also, when I try building `lev`, I get missing packages `stdune` and `fiber`. How is a user expected pull those? Should they be vendored as in this repo?

**Comment by rgrinberg** [comment]
There's no rush, take your time. Everything should be vendored in this PR.

**Comment by ulugbekna** [comment]
> Everything should be vendored in this PR.

I meant when I checkout `rgrinberg/lev` repo and try to build it, I get the errors.

**Comment by rgrinberg** [comment]
That repo relies on some unreleased packages that exist in the dune repository. You can obtain them by pinning the dune repo.

Rudi.

**Comment by ulugbekna** [comment]
hmm, I don't know whether it's a coincidence or not, but with this PR's ocaml-lsp installed, I got ocaml-lsp consuming ~100% CPU sometimes

image

What should we do? Ask contributors to try this PR perhaps and see if they get the same problem? I could look into what's consuming so much CPU if you give me pointers on how to debug that. 

---

Also, regarding building `lev`. When I try to pin packages in the dune repo, I get package version conflict where the packages require dune >= 3.0.0. Any idea how I could pin those packages? 

```
[ERROR] Package conflict!
  * Missing dependency:
    - dune >= 3.0
    no matching version
```

**Comment by rgrinberg** [comment]
> hmm, I don't know whether it's a coincidence or not, but with this PR's ocaml-lsp installed, I got ocaml-lsp consuming ~100% CPU sometimes

What is your OS? Try sampling the stack trace and see if it's `select` that is busy polling? There was a problem like with lev earlier, but I thought I fixed it. This usually happens when libev says some fd is ready to read/write, but we aren't interested in reading/writing from it. In such a case, we should stop watching for events on that fd.

> Also, regarding building lev. When I try to pin packages in the dune repo, I get package version conflict where the packages require dune >= 3.0.0. Any idea how I could pin those packages?

When you pin dune from the development repository, you should specify the version manually. So instead of `opam pin dune .`, it should be `opam pin dune.3.0.0 .`.

**Comment by ulugbekna** [comment]
> What is your OS? 

I'm on macos (intel processor). 

> Try sampling the stack trace and see if it's select that is busy polling? 

Should I use `perf` for that? 

> When you pin dune from the development repository, you should specify the version manually. So instead of opam pin dune ., it should be opam pin dune.3.0.0 ..

Thanks, I'll try that tomorrow

**Comment by rgrinberg** [comment]
There is no perf on macos. But there is `man sample`.

**Comment by rgrinberg** [comment]
@tatchi do you mind giving this PR a try on windows? There's nothing specific to test, just general use.

**Comment by tatchi** [comment]
> @tatchi do you mind giving this PR a try on windows? There's nothing specific to test, just general use.

@rgrinberg I would like to but I don't have a windows machine 😬 I'm running on macOS (intel processor)

**Comment by ulugbekna** [comment]
I haven't noticed any problems with this branch for some time. We can go ahead and merge perhaps? People'll create issues if they have problems.

**Comment by rgrinberg** [comment]
I don't think it works on Windows yet unfortunately. Did the busy polling issue disappear for you?

**Comment by ulugbekna** [comment]
I haven’t experienced it since I reported it the first time, so I thought
if that’s only me slowing down the merge, we can as well go ahead with it

Ulugbek

**Comment by mnxn** [comment]
On Windows:
```
Assertion failed: ("libev: ev_signal_start called with illegal signal number", w->signum > 0 && w->signum < EV_NSIG), file submodules/lev/lev/vendor/ev.c, line 4569
[Error - 10:46:58 AM] Connection to server got closed. Server will not be restarted.
```

**Comment by rgrinberg** [comment]
Thanks. Should be fixed now.

**Comment by ulugbekna** [comment]
Again hitting CPU usage 99%. 

`sample <pid>` output in the file: 

[sample.txt](https://github.com/ocaml/ocaml-lsp/files/7961110/sample.txt)

**Comment by rgrinberg** [comment]
Thanks. Do you have an idea on how to reproduce this?

From the sample, it appears that select is firing. Which usually means that some fd is readable/writeable but we aren't reading/from it.

**Comment by ulugbekna** [comment]
I’m afraid I don’t know how to reproduce this specifically. I’m just doing usual development on ocaml-lsp codebase (last time it was vscode ocaml platform) switching between various source files and editing. I also have dune building in watch mode

**Comment by ulugbekna** [comment]
With this https://github.com/rgrinberg/lev/commit/c73e9e317b65a705cb3c672fe1c989d5dcb695ef, ocamllsp seems to work great! 0% CPU :-) 

I noticed saving a file a bunch of times with high frequency can bump the cpu usage up to ~14%, but that's expected and out of ordinary use of ocamllsp.

**Comment by rgrinberg** [comment]
Thanks. I updated the PR. If everything is ok on Windows I will merge.

**Comment by mnxn** [comment]
Working with no problems on Windows for me.

**Pull request merged**
