### PR TITLE
Enable short paths by default

### PR DESCRIPTION
**Pull request by rgrinberg**
And also fix the ensuing bug in pretty printing of signatures

### CODE REVIEW

**Comment by voodoos** [comment]
You might want to remove the workaround "fixing" the bug, we have now a more robust fix in https://github.com/ocaml/merlin/pull/1334

**Comment by rgrinberg** [comment]
The last commit changes the code to use an environment consistent with how `ocamlc -i` works.

**Review by tmattio — APPROVED** [review]
I'm not familiar enough with Merlin to give an enlightened review, but this LGTM from the regression test

**Review by voodoos — APPROVED** [review]
LGTM too

**Pull request merged**
