### PR TITLE
Update npm packages

### PR DESCRIPTION
**Pull request by rgrinberg**
I've updated everything except for vscode-jsonrpc. Updating this package breaks
our custom requests.

### CODE REVIEW

**Comment by mnxn** [comment]
I think the update of `vscode-languageserver-protocol` prevent the tests files from typechecking.

**Comment by rgrinberg** [comment]
That’s a shame. Reverted this update for now.

**Review by tmattio — APPROVED** [review]
Tested, did not notice any regression

**Comment by mnxn** [comment]
The CI is still failing with type errors in `src/LanguageServer.ts`. Maybe the update of the `typescript` dependency is causing this? I'm not sure.

**Comment by tmattio** [comment]
Closing in favor of #371 that is based on this PR. I updated the packages that we blocked by the test failures and I addressed the Typescript complaints

**Pull request closed without merging**
